import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("uncleaned_data.csv")
df["address"] = df["address"].fillna("Unknown")
df["state"] = df["address"].str.split(",").str[-1]
df["state"] = df["state"].str.strip().str.title()
top_states = df["state"].value_counts().head(5)
df["id"] = pd.to_numeric(df["id"], errors="coerce")
clean_ids = df["id"].dropna()
plt.figure(figsize=(8, 5))
top_states.plot(kind="bar")
plt.title("Top 5 States by Number of Customers")
plt.xlabel("State")
plt.ylabel("Number of Customers")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 5))
plt.hist(clean_ids, bins=10, edgecolor="black")
plt.title("Distribution of Customer IDs")
plt.xlabel("Customer ID")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()